export enum DosageError {
  EMPTY = "EMPTY",
  SEQUENCE = "SEQUENCE",
  BOUNDS_CODE = "BOUNDS_CODE",
  BOUNDS_VALUE = "BOUNDS_VALUE",
  FREQUENCY = "FREQUENCY",
  PERIOD = "PERIOD",
  PERIOD_UNIT = "PERIOD_UNIT",
  DAY_OF_WEEK = "DAY_OF_WEEK",
  DOSE_RATE = "DOSE_RATE",
  DOSE_TYPE = "DOSE_TYPE",
  DOSE = "DOSE",
}
