name: Deployment on Testserver
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploying Frontends
    runs-on: ubuntu-latest
    steps:
      - name: Executing SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /home/linkedcare-demonstrator/
            git pull
            npm run build
            rm -rf /var/www/html/*
            cp -a ./dist/. /var/www/html/
            cp -a /var/www/html/home/. /var/www/html/
            rm -rf /var/www/html/home/
